-- =====================================================================
-- Migration 0030: Open ("unfixed") stall capacity
--
-- Two inventory modes per event, chosen by the admin:
--   'fixed'   — exactly what already existed before this migration: the
--               admin configures stall_types (with independent pricing,
--               and optionally monopoly rules) and generates an exact
--               number of numbered stalls per type from the Stall Types
--               / Stall Inventory admin tabs. Nothing about that changes.
--   'unfixed' — the admin sets one Total Stall Capacity number for the
--               whole event (in half-stall-equivalent units — see
--               full_stall_unit_ratio below) plus a flat Half Stall
--               Price and Full Stall Price. Individual `stalls` rows are
--               never pre-generated by the admin; they're minted lazily,
--               one at a time, the moment a customer actually books
--               (see reserve_open_stall() below), and reused from a
--               pool of previously-cancelled slots before minting a new
--               one. This means an unfixed event's `stalls` table only
--               ever contains as many rows as have been booked at least
--               once — never the full theoretical capacity.
--
-- Why build it this way instead of a parallel booking system: every
-- downstream piece (reservations, monopoly checks, registrations,
-- negotiation, payments, invoices, cancellation-releases-the-stall) is
-- already written against `stalls` + `stall_types` + `stall_reservations`
-- + `stall_allocations`. An unfixed-mode booking still ends up as one
-- ordinary non_monopoly stall_type + stall row going through the exact
-- same reserve_stall()/convert_reservation_to_booking()/cancel_booking()
-- functions untouched — so cancellations and refunds already correctly
-- free up capacity for reuse with zero new release-logic to write or
-- get wrong: a cancelled/expired stall simply goes back to
-- status='available', which both (a) is no longer counted as "consumed"
-- capacity by the view below, and (b) is the first slot
-- reserve_open_stall() will hand out next time, before it ever mints a
-- new one.
-- =====================================================================

create type public.event_stall_mode as enum ('fixed', 'unfixed');

alter table public.events
  add column stall_mode public.event_stall_mode not null default 'fixed',
  add column total_stall_capacity int,
  -- How many capacity units a Full stall consumes vs. a Half stall (which
  -- always costs 1 unit). Lives in the database, not application code, so
  -- a future event with a different half/full space ratio never needs a
  -- code change — only a value change on that event's row. Defaults to 2
  -- (a full stall is usually double a half stall's floor space).
  add column full_stall_unit_ratio numeric(6,2) not null default 2
    check (full_stall_unit_ratio > 0);

-- ---------------------------------------------------------------------
-- reserve_open_stall() — the unfixed-mode entry point. Capacity-checks
-- and, if room allows, hands back a stall_reservations row exactly like
-- reserve_stall() does directly — because it IS reserve_stall(), called
-- on a stall this function finds-or-mints first. Everything after this
-- call (booking wizard, payment, negotiation, cancellation) is unaware
-- unfixed mode even exists.
-- ---------------------------------------------------------------------
create or replace function public.reserve_open_stall(
  p_event_id uuid, p_size_type public.stall_size, p_category_id uuid default null
) returns public.stall_reservations
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event public.events%rowtype;
  v_stall_type_id uuid;
  v_needed numeric;
  v_consumed numeric;
  v_remaining numeric;
  v_stall_id uuid;
  v_next_seq int;
  v_stall_number text;
begin
  if auth.uid() is null then
    raise exception 'AUTH_REQUIRED' using errcode = 'P0001';
  end if;

  -- Lock the event row for the rest of this transaction: this is what
  -- makes "never go negative" airtight. Two customers racing for the
  -- last unit of capacity cannot both pass the check below — the second
  -- transaction blocks here until the first commits (freeing the lock),
  -- and by then the first booking's consumed-capacity is already
  -- reflected in what the second transaction reads.
  select * into v_event from public.events where id = p_event_id for update;
  if not found then
    raise exception 'EVENT_NOT_FOUND' using errcode = 'P0001';
  end if;
  if v_event.stall_mode <> 'unfixed' then
    raise exception 'EVENT_NOT_OPEN_CAPACITY' using errcode = 'P0001';
  end if;

  select id into v_stall_type_id
  from public.stall_types
  where event_id = p_event_id and size_type = p_size_type and monopoly_type = 'non_monopoly'
  limit 1;
  if v_stall_type_id is null then
    raise exception 'STALL_TYPE_NOT_CONFIGURED' using errcode = 'P0001';
  end if;

  v_needed := case when p_size_type = 'full' then v_event.full_stall_unit_ratio else 1 end;

  select coalesce(sum(case when st.size_type = 'full' then v_event.full_stall_unit_ratio else 1 end), 0)
    into v_consumed
  from public.stalls s
  join public.stall_types st on st.id = s.stall_type_id
  where s.event_id = p_event_id and s.status <> 'available';

  v_remaining := coalesce(v_event.total_stall_capacity, 0) - v_consumed;
  if v_remaining < v_needed then
    raise exception 'CAPACITY_UNAVAILABLE' using errcode = 'P0001';
  end if;

  -- Reuse a slot freed by an earlier cancellation/expiry before minting a
  -- new one, so the stalls table never grows past what's actually needed.
  -- "for update skip locked" is belt-and-suspenders: the event-row lock
  -- above already serializes every open-capacity booking for this event,
  -- so nothing else can be racing for this same row.
  select id into v_stall_id
  from public.stalls
  where event_id = p_event_id and stall_type_id = v_stall_type_id and status = 'available'
  limit 1
  for update skip locked;

  if v_stall_id is null then
    select count(*) + 1 into v_next_seq
    from public.stalls where event_id = p_event_id and stall_type_id = v_stall_type_id;
    v_stall_number := (case when p_size_type = 'full' then 'F-' else 'H-' end) || v_next_seq;

    insert into public.stalls (event_id, stall_type_id, stall_number, status)
    values (p_event_id, v_stall_type_id, v_stall_number, 'available')
    returning id into v_stall_id;
  end if;

  return public.reserve_stall(v_stall_id, p_category_id);
end;
$$;

grant execute on function public.reserve_open_stall(uuid, public.stall_size, uuid) to authenticated;

-- ---------------------------------------------------------------------
-- event_listing_v — extended so every existing consumer (Home cards,
-- the public events grid, the admin events list) keeps working
-- unchanged: total_stalls/available_stalls now mean "current bookable
-- capacity" regardless of mode (physical stall counts for fixed events,
-- exactly as before; remaining capacity units for unfixed events, which
-- otherwise would misleadingly read "0 of 0" before any stall has ever
-- been minted). starting_price_paise, half_stall_price_paise and
-- full_stall_price_paise now come straight from stall_types so a price
-- shows up the moment the admin sets it — even before any stall exists
-- to derive it from.
--
-- As in 0029: Postgres requires CREATE OR REPLACE VIEW to keep every
-- existing column in its original name/order/type and only APPEND new
-- ones at the end, so the 20 columns 0029 already produced (the original
-- 18 from 0004, plus maps_url/expected_crowd) are kept in that exact
-- order below, and this migration's 5 new columns are appended after.
-- ---------------------------------------------------------------------
create or replace view public.event_listing_v as
select
  e.id, e.name, e.slug, e.description, e.banner_url, e.venue, e.address, e.city,
  e.event_date, e.end_date, e.start_time, e.end_time, e.status,
  e.registration_start_at, e.registration_end_at,
  case
    when e.stall_mode = 'unfixed' then coalesce(e.total_stall_capacity, 0)::bigint
    else count(s.id)
  end as total_stalls,
  case
    when e.stall_mode = 'unfixed' then
      greatest(
        coalesce(e.total_stall_capacity, 0) - coalesce(sum(
          case when s.status <> 'available' then
            case when st.size_type = 'full' then e.full_stall_unit_ratio else 1 end
          else 0 end
        ), 0),
        0
      )::bigint
    else count(s.id) filter (where s.status = 'available')
  end as available_stalls,
  (select min(price_paise) from public.stall_types where event_id = e.id) as starting_price_paise,
  e.maps_url, e.expected_crowd,
  e.stall_mode, e.total_stall_capacity, e.full_stall_unit_ratio,
  (select price_paise from public.stall_types
     where event_id = e.id and size_type = 'half' order by price_paise limit 1) as half_stall_price_paise,
  (select price_paise from public.stall_types
     where event_id = e.id and size_type = 'full' order by price_paise limit 1) as full_stall_price_paise
from public.events e
left join public.stalls s on s.event_id = e.id
left join public.stall_types st on st.id = s.stall_type_id
group by e.id;
